/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package topique.view;

import javax.swing.JOptionPane;
import topique.model.Aluno;

public class FormHomeA extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormHomeA.class.getName());

    /**
     * Creates new form FormLogin
     *
     * @param aluno
     */
    public FormHomeA(Aluno aluno) {
        initComponents();
        setLocationRelativeTo(null);

        homeATextSaudacao.setText(aluno.saudacao());
    }

    public FormHomeA() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        homeMTextSolicitarCorrida = new javax.swing.JLabel();
        homeASairButton = new javax.swing.JButton();
        homeMTextUsarLoc = new javax.swing.JLabel();
        homeAToggleButton = new javax.swing.JToggleButton();
        homeATextLeiaRegras = new javax.swing.JLabel();
        homeATextLeiaRegras1 = new javax.swing.JLabel();
        homeAButtonRegras = new javax.swing.JButton();
        homeACheckBox = new javax.swing.JCheckBox();
        homeAButtonSolicitarCorrida = new javax.swing.JButton();
        homeATextFieldLoc = new javax.swing.JTextField();
        homeATextSaudacao = new javax.swing.JLabel();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setForeground(java.awt.Color.white);

        homeMTextSolicitarCorrida.setFont(new java.awt.Font("Gadugi", 1, 26)); // NOI18N
        homeMTextSolicitarCorrida.setText("SOLICITAR CORRIDA");
        homeMTextSolicitarCorrida.setName(""); // NOI18N
        homeMTextSolicitarCorrida.setOpaque(true);

        homeASairButton.setFont(new java.awt.Font("Gadugi", 1, 20)); // NOI18N
        homeASairButton.setText("Sair");
        homeASairButton.addActionListener(this::homeASairButtonActionPerformed);

        homeMTextUsarLoc.setFont(new java.awt.Font("Gadugi", 1, 26)); // NOI18N
        homeMTextUsarLoc.setText("Usar localização atual?");
        homeMTextUsarLoc.setName(""); // NOI18N
        homeMTextUsarLoc.setOpaque(true);

        homeAToggleButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        homeAToggleButton.setText("NÃO");
        homeAToggleButton.addActionListener(this::homeAToggleButtonActionPerformed);

        homeATextLeiaRegras.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        homeATextLeiaRegras.setText("Antes de solicitar a corrida, leia as regras abaixo");

        homeATextLeiaRegras1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        homeATextLeiaRegras1.setText("e marque os termos de uso");

        homeAButtonRegras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        homeAButtonRegras.setText("REGRAS");
        homeAButtonRegras.addActionListener(this::homeAButtonRegrasActionPerformed);

        homeACheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        homeACheckBox.setText("* Li atentamente e estou plenamente de acordo");
        homeACheckBox.addActionListener(this::homeACheckBoxActionPerformed);

        homeAButtonSolicitarCorrida.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        homeAButtonSolicitarCorrida.setText("SOLICITAR CORRIDA");
        homeAButtonSolicitarCorrida.addActionListener(this::homeAButtonSolicitarCorridaActionPerformed);

        homeATextSaudacao.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        homeATextSaudacao.setText("default");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(homeATextLeiaRegras)
                .addGap(0, 52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(homeATextLeiaRegras1)
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(homeAButtonRegras, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(221, 221, 221))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(homeACheckBox)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(homeAButtonSolicitarCorrida)
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(homeAToggleButton)
                        .addGap(228, 228, 228))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(homeATextSaudacao)
                                .addGap(158, 158, 158)
                                .addComponent(homeASairButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(homeMTextSolicitarCorrida)
                                .addComponent(homeMTextUsarLoc)))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(homeATextFieldLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeASairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeATextSaudacao))
                .addGap(17, 17, 17)
                .addComponent(homeMTextSolicitarCorrida)
                .addGap(37, 37, 37)
                .addComponent(homeMTextUsarLoc)
                .addGap(18, 18, 18)
                .addComponent(homeAToggleButton)
                .addGap(18, 18, 18)
                .addComponent(homeATextFieldLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(homeATextLeiaRegras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeATextLeiaRegras1)
                .addGap(32, 32, 32)
                .addComponent(homeAButtonRegras, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(homeACheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(homeAButtonSolicitarCorrida)
                .addGap(85, 85, 85))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeASairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeASairButtonActionPerformed
        // TODO add your handling code here:
        FormLogin login = new FormLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeASairButtonActionPerformed

    private void homeAToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeAToggleButtonActionPerformed

        if (homeAToggleButton.isSelected()) {
            homeAToggleButton.setText("SIM");
            homeATextFieldLoc.setVisible(false);
        } else {
            homeAToggleButton.setText("NÃO");
            homeATextFieldLoc.setVisible(true);
        }

        // Atualiza o layout da tela
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_homeAToggleButtonActionPerformed

    private void homeAButtonRegrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeAButtonRegrasActionPerformed
        // TODO add your handling code here:
        FormHomeARegras homeARegras = new FormHomeARegras();
        homeARegras.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeAButtonRegrasActionPerformed

    private void homeAButtonSolicitarCorridaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeAButtonSolicitarCorridaActionPerformed
        if (homeACheckBox.isSelected()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Corrida solicitada!\n"
                    + "Motorista: Lucas\n"
                    + "Placa: RQM4C98\n"
                    + "Tempo estimado: 15 minutos"
            );
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "É necessário confirmar que leu as regras!",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        }

    }//GEN-LAST:event_homeAButtonSolicitarCorridaActionPerformed

    private void homeACheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeACheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeACheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormHomeA().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeAButtonRegras;
    private javax.swing.JButton homeAButtonSolicitarCorrida;
    private javax.swing.JCheckBox homeACheckBox;
    private javax.swing.JButton homeASairButton;
    private javax.swing.JTextField homeATextFieldLoc;
    private javax.swing.JLabel homeATextLeiaRegras;
    private javax.swing.JLabel homeATextLeiaRegras1;
    private javax.swing.JLabel homeATextSaudacao;
    private javax.swing.JToggleButton homeAToggleButton;
    private javax.swing.JLabel homeMTextSolicitarCorrida;
    private javax.swing.JLabel homeMTextUsarLoc;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
