/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package topique.view;

/**
 *
 * @author rafas
 */
public class FormCadastro extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCadastro.class.getName());

    /**
     * Creates new form FormLogin
     */
    public FormCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        cadastroBoxUser = new java.awt.TextField();
        cadastroTextUser = new javax.swing.JLabel();
        cadastroTextPassword = new javax.swing.JLabel();
        cadastroEntrarButton = new javax.swing.JButton();
        cadastroCadastrarButton = new javax.swing.JButton();
        cadastroBoxPassword = new javax.swing.JPasswordField();
        cadastroBoxPassword1 = new javax.swing.JPasswordField();
        cadastroTextPassword1 = new javax.swing.JLabel();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setForeground(java.awt.Color.white);

        cadastroBoxUser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cadastroBoxUser.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        cadastroBoxUser.addActionListener(this::cadastroBoxUserActionPerformed);

        cadastroTextUser.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        cadastroTextUser.setText("Usuário");
        cadastroTextUser.setName(""); // NOI18N
        cadastroTextUser.setOpaque(true);

        cadastroTextPassword.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        cadastroTextPassword.setText("Senha");
        cadastroTextPassword.setName(""); // NOI18N
        cadastroTextPassword.setOpaque(true);

        cadastroEntrarButton.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        cadastroEntrarButton.setText("Já tenho uma conta");
        cadastroEntrarButton.addActionListener(this::cadastroEntrarButtonActionPerformed);

        cadastroCadastrarButton.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        cadastroCadastrarButton.setText("Cadastrar");
        cadastroCadastrarButton.addActionListener(this::cadastroCadastrarButtonActionPerformed);

        cadastroBoxPassword.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N

        cadastroBoxPassword1.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N

        cadastroTextPassword1.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        cadastroTextPassword1.setText("Repita a senha");
        cadastroTextPassword1.setName(""); // NOI18N
        cadastroTextPassword1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastroEntrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cadastroTextUser)
                        .addComponent(cadastroTextPassword)
                        .addComponent(cadastroBoxUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadastroCadastrarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                        .addComponent(cadastroBoxPassword)
                        .addComponent(cadastroBoxPassword1)
                        .addComponent(cadastroTextPassword1)))
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(cadastroTextUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastroBoxUser, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(cadastroTextPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastroBoxPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cadastroTextPassword1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastroBoxPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(cadastroCadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cadastroEntrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroBoxUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroBoxUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroBoxUserActionPerformed

    private void cadastroCadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroCadastrarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroCadastrarButtonActionPerformed

    private void cadastroEntrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroEntrarButtonActionPerformed
        // TODO add your handling code here:
        FormLogin login = new FormLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cadastroEntrarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCadastro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cadastroBoxPassword;
    private javax.swing.JPasswordField cadastroBoxPassword1;
    private java.awt.TextField cadastroBoxUser;
    private javax.swing.JButton cadastroCadastrarButton;
    private javax.swing.JButton cadastroEntrarButton;
    private javax.swing.JLabel cadastroTextPassword;
    private javax.swing.JLabel cadastroTextPassword1;
    private javax.swing.JLabel cadastroTextUser;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
