/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package topique.view;

import javax.swing.JOptionPane;
import topique.dao.AlunoDAO;
import topique.model.Aluno;

/**
 *
 * @author rafas
 */
public class FormLogin extends javax.swing.JFrame {

    public static AlunoDAO dao = new AlunoDAO();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormLogin.class.getName());

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
        dao.leArquivo();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        loginBoxCpf = new java.awt.TextField();
        loginTextCpf = new javax.swing.JLabel();
        loginTextPassword = new javax.swing.JLabel();
        loginEntrarButton = new javax.swing.JButton();
        loginCadastrarButton = new javax.swing.JButton();
        loginBoxPassword = new javax.swing.JPasswordField();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setForeground(java.awt.Color.white);

        loginBoxCpf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        loginBoxCpf.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        loginBoxCpf.addActionListener(this::loginBoxCpfActionPerformed);

        loginTextCpf.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        loginTextCpf.setText("CPF");
        loginTextCpf.setName(""); // NOI18N
        loginTextCpf.setOpaque(true);

        loginTextPassword.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        loginTextPassword.setText("Senha");
        loginTextPassword.setName(""); // NOI18N
        loginTextPassword.setOpaque(true);

        loginEntrarButton.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        loginEntrarButton.setText("Entrar");
        loginEntrarButton.addActionListener(this::loginEntrarButtonActionPerformed);

        loginCadastrarButton.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        loginCadastrarButton.setText("Cadastrar");
        loginCadastrarButton.addActionListener(this::loginCadastrarButtonActionPerformed);

        loginBoxPassword.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginTextCpf)
                    .addComponent(loginTextPassword)
                    .addComponent(loginBoxCpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginEntrarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginCadastrarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(loginBoxPassword))
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(loginTextCpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginBoxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(loginTextPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginBoxPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(loginEntrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(loginCadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBoxCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBoxCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBoxCpfActionPerformed

    private void loginCadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginCadastrarButtonActionPerformed
        // TODO add your handling code here:
        FormCadastro cadastro = new FormCadastro();
        cadastro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginCadastrarButtonActionPerformed

    private void loginEntrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginEntrarButtonActionPerformed
        // TODO add your handling code here:
        String cpf = loginBoxCpf.getText();
        String senha = new String(loginBoxPassword.getPassword());

        // Verifica campos vazios
        if (cpf.isEmpty() || senha.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Preencha CPF e Senha!",
                    "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Login motorista
        if (cpf.equals("123") && senha.equals("admin")) {
            JOptionPane.showMessageDialog(this, "Login de motorista realizado!");
            loginBoxCpf.setText("");
            loginBoxPassword.setText("");

            FormHomeM home = new FormHomeM();
            home.setVisible(true);
            this.dispose();
            return;
        }

        Aluno aluno = dao.buscarPorCpf(cpf);

        if (aluno == null) {
            JOptionPane.showMessageDialog(this,
                    "CPF não encontrado!",
                    "Erro", JOptionPane.ERROR_MESSAGE);

            loginBoxCpf.setText("");
            loginBoxPassword.setText("");
            loginBoxCpf.requestFocus();
            return;
        }

        // Valida senha
        if (!aluno.getSenha().equals(senha)) {
            JOptionPane.showMessageDialog(this,
                    "Senha incorreta!",
                    "Erro", JOptionPane.ERROR_MESSAGE);

            loginBoxPassword.setText("");
            loginBoxPassword.requestFocus();
            return;
        }

        JOptionPane.showMessageDialog(this, "Login realizado com sucesso!");

        loginBoxCpf.setText("");
        loginBoxPassword.setText("");
        loginBoxCpf.requestFocus();

        // CHAMAR TELA DO ALUNO
    }//GEN-LAST:event_loginEntrarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField loginBoxCpf;
    private javax.swing.JPasswordField loginBoxPassword;
    private javax.swing.JButton loginCadastrarButton;
    private javax.swing.JButton loginEntrarButton;
    private javax.swing.JLabel loginTextCpf;
    private javax.swing.JLabel loginTextPassword;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
