/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package topique.view;

public class FormHomeARegras extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormHomeARegras.class.getName());

    /**
     * Creates new form FormLogin
     */
    public FormHomeARegras() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        homeMTextSolicitarCorrida = new javax.swing.JLabel();
        homeAVoltarButton = new javax.swing.JButton();
        homeMTextRegras1 = new javax.swing.JLabel();
        homeMTextRegras2 = new javax.swing.JLabel();
        homeMTextRegras3 = new javax.swing.JLabel();
        homeMTextRegras4 = new javax.swing.JLabel();
        homeMTextRegras5 = new javax.swing.JLabel();
        homeMTextRegras6 = new javax.swing.JLabel();
        homeMTextRegras7 = new javax.swing.JLabel();
        homeMTextRegras8 = new javax.swing.JLabel();
        homeMTextRegras9 = new javax.swing.JLabel();
        homeMTextRegras10 = new javax.swing.JLabel();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setForeground(java.awt.Color.white);

        homeMTextSolicitarCorrida.setFont(new java.awt.Font("Gadugi", 1, 26)); // NOI18N
        homeMTextSolicitarCorrida.setText("REGRAS");
        homeMTextSolicitarCorrida.setName(""); // NOI18N
        homeMTextSolicitarCorrida.setOpaque(true);

        homeAVoltarButton.setFont(new java.awt.Font("Gadugi", 1, 20)); // NOI18N
        homeAVoltarButton.setText("Voltar");
        homeAVoltarButton.addActionListener(this::homeAVoltarButtonActionPerformed);

        homeMTextRegras1.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        homeMTextRegras1.setText("Preço fixo por passageiro: Cada corrida terá um");
        homeMTextRegras1.setName(""); // NOI18N
        homeMTextRegras1.setOpaque(true);

        homeMTextRegras2.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        homeMTextRegras2.setText(" custo fixo de R$ 20,00 por pessoa, independente");
        homeMTextRegras2.setName(""); // NOI18N
        homeMTextRegras2.setOpaque(true);

        homeMTextRegras3.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        homeMTextRegras3.setText(" da distância percorrida.");
        homeMTextRegras3.setName(""); // NOI18N
        homeMTextRegras3.setOpaque(true);

        homeMTextRegras4.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        homeMTextRegras4.setText("Pontualidade no ponto de coleta: Os passageiros");
        homeMTextRegras4.setName(""); // NOI18N
        homeMTextRegras4.setOpaque(true);

        homeMTextRegras5.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        homeMTextRegras5.setText("devem estar no ponto de coleta com 5 minutos");
        homeMTextRegras5.setName(""); // NOI18N
        homeMTextRegras5.setOpaque(true);

        homeMTextRegras6.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        homeMTextRegras6.setText(" de antecedência.");
        homeMTextRegras6.setName(""); // NOI18N
        homeMTextRegras6.setOpaque(true);

        homeMTextRegras7.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        homeMTextRegras7.setText("Atrasos podem resultar em perda da viagem. ");
        homeMTextRegras7.setName(""); // NOI18N
        homeMTextRegras7.setOpaque(true);

        homeMTextRegras8.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        homeMTextRegras8.setText("Cancelamento de viagem: Cancelamentos devem ser");
        homeMTextRegras8.setName(""); // NOI18N
        homeMTextRegras8.setOpaque(true);

        homeMTextRegras9.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        homeMTextRegras9.setText(" feitos com no mínimo 2 horas de antecedência.");
        homeMTextRegras9.setName(""); // NOI18N
        homeMTextRegras9.setOpaque(true);

        homeMTextRegras10.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        homeMTextRegras10.setText("Caso contrário, a corrida será cobrada normalmente.");
        homeMTextRegras10.setName(""); // NOI18N
        homeMTextRegras10.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(homeMTextRegras10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(173, 173, 173)
                            .addComponent(homeMTextRegras3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(homeMTextRegras1)
                                    .addComponent(homeMTextRegras2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(homeMTextRegras4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(homeMTextRegras7)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(homeMTextRegras5)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(124, 124, 124)
                                                    .addComponent(homeMTextRegras6))))))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(homeAVoltarButton)
                            .addGap(97, 97, 97)
                            .addComponent(homeMTextSolicitarCorrida))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addComponent(homeMTextRegras8))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(homeMTextRegras9))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeMTextSolicitarCorrida)
                    .addComponent(homeAVoltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(homeMTextRegras1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeMTextRegras2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeMTextRegras3)
                .addGap(72, 72, 72)
                .addComponent(homeMTextRegras4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeMTextRegras5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeMTextRegras6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeMTextRegras7)
                .addGap(84, 84, 84)
                .addComponent(homeMTextRegras8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeMTextRegras9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeMTextRegras10)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeAVoltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeAVoltarButtonActionPerformed
        // TODO add your handling code here:
        FormHomeA homeA = new FormHomeA();
        homeA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeAVoltarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormHomeARegras().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeAVoltarButton;
    private javax.swing.JLabel homeMTextRegras1;
    private javax.swing.JLabel homeMTextRegras10;
    private javax.swing.JLabel homeMTextRegras2;
    private javax.swing.JLabel homeMTextRegras3;
    private javax.swing.JLabel homeMTextRegras4;
    private javax.swing.JLabel homeMTextRegras5;
    private javax.swing.JLabel homeMTextRegras6;
    private javax.swing.JLabel homeMTextRegras7;
    private javax.swing.JLabel homeMTextRegras8;
    private javax.swing.JLabel homeMTextRegras9;
    private javax.swing.JLabel homeMTextSolicitarCorrida;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
