/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package topique.view;

import topique.model.Motorista;

public class FormHomeM extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormHomeM.class.getName());

    /**
     * Creates new form FormLogin
     *
     * @param motorista
     */
    public FormHomeM(Motorista motorista) {
        initComponents();
        setLocationRelativeTo(null);

        homeMTextSaudacao.setText(motorista.saudacao());
    }

    public FormHomeM() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        homeMTextRotasDoDia = new javax.swing.JLabel();
        homeMSairButton = new javax.swing.JButton();
        homeMTextAluno1 = new javax.swing.JLabel();
        homeMTextBairro1 = new javax.swing.JLabel();
        homeMTextEndereco1 = new javax.swing.JLabel();
        homeMTextAluno2 = new javax.swing.JLabel();
        homeMTextBairro2 = new javax.swing.JLabel();
        homeMTextEndereco2 = new javax.swing.JLabel();
        homeMTextEndereco3 = new javax.swing.JLabel();
        homeMTextBairro3 = new javax.swing.JLabel();
        homeMTextAluno3 = new javax.swing.JLabel();
        homeMTextAluno4 = new javax.swing.JLabel();
        homeMTextBairro4 = new javax.swing.JLabel();
        homeMTextEndereco4 = new javax.swing.JLabel();
        homeMCheckbox1 = new java.awt.Checkbox();
        homeMTextEntregue1 = new javax.swing.JLabel();
        homeMTextEntregue2 = new javax.swing.JLabel();
        homeMCheckbox2 = new java.awt.Checkbox();
        homeMTextEntregue3 = new javax.swing.JLabel();
        homeMCheckbox3 = new java.awt.Checkbox();
        homeMTextEntregue4 = new javax.swing.JLabel();
        homeMCheckbox4 = new java.awt.Checkbox();
        homeMTextSaudacao = new javax.swing.JLabel();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setForeground(java.awt.Color.white);

        homeMTextRotasDoDia.setFont(new java.awt.Font("Gadugi", 1, 26)); // NOI18N
        homeMTextRotasDoDia.setText("ROTAS DO DIA");
        homeMTextRotasDoDia.setName(""); // NOI18N
        homeMTextRotasDoDia.setOpaque(true);

        homeMSairButton.setFont(new java.awt.Font("Gadugi", 1, 20)); // NOI18N
        homeMSairButton.setText("Sair");
        homeMSairButton.addActionListener(this::homeMSairButtonActionPerformed);

        homeMTextAluno1.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        homeMTextAluno1.setText("Cinthia Cristina");
        homeMTextAluno1.setName(""); // NOI18N
        homeMTextAluno1.setOpaque(true);

        homeMTextBairro1.setFont(new java.awt.Font("Gadugi", 0, 20)); // NOI18N
        homeMTextBairro1.setText("Mata da Praia");
        homeMTextBairro1.setName(""); // NOI18N
        homeMTextBairro1.setOpaque(true);

        homeMTextEndereco1.setFont(new java.awt.Font("Gadugi", 0, 20)); // NOI18N
        homeMTextEndereco1.setText("R. Moacir Avidos, 380");
        homeMTextEndereco1.setName(""); // NOI18N
        homeMTextEndereco1.setOpaque(true);

        homeMTextAluno2.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        homeMTextAluno2.setText("Elias Silva");
        homeMTextAluno2.setName(""); // NOI18N
        homeMTextAluno2.setOpaque(true);

        homeMTextBairro2.setFont(new java.awt.Font("Gadugi", 0, 20)); // NOI18N
        homeMTextBairro2.setText("Jardim da Penha");
        homeMTextBairro2.setName(""); // NOI18N
        homeMTextBairro2.setOpaque(true);

        homeMTextEndereco2.setFont(new java.awt.Font("Gadugi", 0, 20)); // NOI18N
        homeMTextEndereco2.setText("R. Francisco Eugênio Mussielo, 600");
        homeMTextEndereco2.setName(""); // NOI18N
        homeMTextEndereco2.setOpaque(true);

        homeMTextEndereco3.setFont(new java.awt.Font("Gadugi", 0, 20)); // NOI18N
        homeMTextEndereco3.setText("R. Agenor Amaro dos Santos, 966");
        homeMTextEndereco3.setName(""); // NOI18N
        homeMTextEndereco3.setOpaque(true);

        homeMTextBairro3.setFont(new java.awt.Font("Gadugi", 0, 20)); // NOI18N
        homeMTextBairro3.setText("Jardim Camburi");
        homeMTextBairro3.setName(""); // NOI18N
        homeMTextBairro3.setOpaque(true);

        homeMTextAluno3.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        homeMTextAluno3.setText("Guilherme Paiva");
        homeMTextAluno3.setName(""); // NOI18N
        homeMTextAluno3.setOpaque(true);

        homeMTextAluno4.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        homeMTextAluno4.setText("Rafael Pim");
        homeMTextAluno4.setName(""); // NOI18N
        homeMTextAluno4.setOpaque(true);

        homeMTextBairro4.setFont(new java.awt.Font("Gadugi", 0, 20)); // NOI18N
        homeMTextBairro4.setText("Bairro de Fátima");
        homeMTextBairro4.setName(""); // NOI18N
        homeMTextBairro4.setOpaque(true);

        homeMTextEndereco4.setFont(new java.awt.Font("Gadugi", 0, 20)); // NOI18N
        homeMTextEndereco4.setText("R. Vitória, 134");
        homeMTextEndereco4.setName(""); // NOI18N
        homeMTextEndereco4.setOpaque(true);

        homeMCheckbox1.setName(""); // NOI18N

        homeMTextEntregue1.setFont(new java.awt.Font("Gadugi", 0, 20)); // NOI18N
        homeMTextEntregue1.setText("Entregue");
        homeMTextEntregue1.setName(""); // NOI18N
        homeMTextEntregue1.setOpaque(true);

        homeMTextEntregue2.setFont(new java.awt.Font("Gadugi", 0, 20)); // NOI18N
        homeMTextEntregue2.setText("Entregue");
        homeMTextEntregue2.setName(""); // NOI18N
        homeMTextEntregue2.setOpaque(true);

        homeMCheckbox2.setName(""); // NOI18N

        homeMTextEntregue3.setFont(new java.awt.Font("Gadugi", 0, 20)); // NOI18N
        homeMTextEntregue3.setText("Entregue");
        homeMTextEntregue3.setName(""); // NOI18N
        homeMTextEntregue3.setOpaque(true);

        homeMCheckbox3.setName(""); // NOI18N

        homeMTextEntregue4.setFont(new java.awt.Font("Gadugi", 0, 20)); // NOI18N
        homeMTextEntregue4.setText("Entregue");
        homeMTextEntregue4.setName(""); // NOI18N
        homeMTextEntregue4.setOpaque(true);

        homeMCheckbox4.setName(""); // NOI18N

        homeMTextSaudacao.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        homeMTextSaudacao.setText("default");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeMTextAluno2)
                    .addComponent(homeMTextBairro2)
                    .addComponent(homeMTextBairro1)
                    .addComponent(homeMTextAluno1)
                    .addComponent(homeMTextAluno3)
                    .addComponent(homeMTextEndereco1)
                    .addComponent(homeMTextEndereco2)
                    .addComponent(homeMTextEndereco3)
                    .addComponent(homeMTextBairro3)
                    .addComponent(homeMTextAluno4)
                    .addComponent(homeMTextBairro4)
                    .addComponent(homeMTextEndereco4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(homeMCheckbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(23, 23, 23))
                        .addComponent(homeMTextEntregue1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(homeMTextEntregue2)
                    .addComponent(homeMTextEntregue3)
                    .addComponent(homeMTextEntregue4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(homeMCheckbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(homeMCheckbox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(homeMCheckbox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeMTextSaudacao)
                .addGap(146, 146, 146)
                .addComponent(homeMSairButton)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(homeMTextRotasDoDia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(homeMSairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(homeMTextSaudacao))
                        .addGap(26, 26, 26)
                        .addComponent(homeMTextRotasDoDia)
                        .addGap(33, 33, 33)
                        .addComponent(homeMTextAluno1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homeMTextBairro1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(homeMTextEntregue1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homeMCheckbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeMTextEndereco1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(homeMTextAluno2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homeMTextBairro2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(homeMTextEntregue2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homeMCheckbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeMTextEndereco2)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(homeMTextAluno3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homeMTextBairro3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(homeMTextEntregue3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homeMCheckbox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeMTextEndereco3)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(homeMTextAluno4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homeMTextBairro4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(homeMTextEntregue4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homeMCheckbox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeMTextEndereco4)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeMSairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeMSairButtonActionPerformed
        // TODO add your handling code here:
        FormLogin login = new FormLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeMSairButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormHomeM().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox homeMCheckbox1;
    private java.awt.Checkbox homeMCheckbox2;
    private java.awt.Checkbox homeMCheckbox3;
    private java.awt.Checkbox homeMCheckbox4;
    private javax.swing.JButton homeMSairButton;
    private javax.swing.JLabel homeMTextAluno1;
    private javax.swing.JLabel homeMTextAluno2;
    private javax.swing.JLabel homeMTextAluno3;
    private javax.swing.JLabel homeMTextAluno4;
    private javax.swing.JLabel homeMTextBairro1;
    private javax.swing.JLabel homeMTextBairro2;
    private javax.swing.JLabel homeMTextBairro3;
    private javax.swing.JLabel homeMTextBairro4;
    private javax.swing.JLabel homeMTextEndereco1;
    private javax.swing.JLabel homeMTextEndereco2;
    private javax.swing.JLabel homeMTextEndereco3;
    private javax.swing.JLabel homeMTextEndereco4;
    private javax.swing.JLabel homeMTextEntregue1;
    private javax.swing.JLabel homeMTextEntregue2;
    private javax.swing.JLabel homeMTextEntregue3;
    private javax.swing.JLabel homeMTextEntregue4;
    private javax.swing.JLabel homeMTextRotasDoDia;
    private javax.swing.JLabel homeMTextSaudacao;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
